//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_buttonhint : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.buttonhint_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean TeleportHint
        {
            get
            {
                return SteamVR_Actions.buttonhint_TeleportHint;
            }
        }
        
        public virtual SteamVR_Action_Boolean GameMenuHint
        {
            get
            {
                return SteamVR_Actions.buttonhint_GameMenuHint;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGripHint
        {
            get
            {
                return SteamVR_Actions.buttonhint_GrabGripHint;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinchHint
        {
            get
            {
                return SteamVR_Actions.buttonhint_GrabPinchHint;
            }
        }
        
        public virtual SteamVR_Action_Boolean SteamVRMenuHint
        {
            get
            {
                return SteamVR_Actions.buttonhint_SteamVRMenuHint;
            }
        }
        
        public virtual SteamVR_Action_Vibration HapticHint
        {
            get
            {
                return SteamVR_Actions.buttonhint_HapticHint;
            }
        }
    }
}
